const mockUsers = [
  {
    id: "user_guardian_joao",
    name: "João Almeida",
    email: "joao@email.com",
    role: "guardian",
    phone: "(91) 99999-0000",
    status: "active",
    createdAt: "2026-06-01",
  },
  {
    id: "user_tutor_maria",
    name: "Maria Silva",
    email: "maria@email.com",
    role: "tutor",
    phone: "(91) 98888-0000",
    status: "active",
    createdAt: "2026-06-02",
  },
  {
    id: "user_admin_cognita",
    name: "Equipe Cognita",
    email: "admin@cognitahub.org",
    role: "admin",
    phone: "(91) 97777-0000",
    status: "active",
    createdAt: "2026-06-01",
  },
];

const mockChildren = [
  {
    id: "child_joao",
    guardianId: "user_guardian_joao",
    name: "João Pereira",
    age: 7,
    schoolYear: "2o ano",
    hasFormalDiagnosis: "not_informed",
    status: "active",
    currentMonth: 2,
    tutorName: "Maria Silva",
    mainGoal: "Contagem, comparacao de quantidades e somas simples",
    preferredFormats: ["visual", "concreto", "passo a passo"],
    interests: "objetos do cotidiano, jogos e personagens",
    avoidances: "textos longos e muitas instrucoes ao mesmo tempo",
    currentActivity: "Soma com apoio visual",
    nextSession: "Quinta-feira, 15h",
    createdAt: "2026-06-01",
  },
  {
    id: "child_lia",
    guardianId: "user_guardian_lia",
    name: "Lia Costa",
    age: 9,
    schoolYear: "4o ano",
    hasFormalDiagnosis: true,
    status: "waiting",
    currentMonth: 1,
    tutorName: "Aguardando tutor",
    mainGoal: "Problemas simples do cotidiano e geometria básica",
    preferredFormats: ["concreto", "jogos"],
    interests: "desenhos, blocos e desafios curtos",
    avoidances: "atividades muito abstratas sem exemplo",
    currentActivity: "Comparar quantidades com objetos",
    nextSession: "Aguardando match",
    createdAt: "2026-06-04",
  },
];

const mockLearningProfiles = [
  {
    id: "profile_joao",
    childId: "child_joao",
    preferredFormats: ["visual", "concrete", "step_by_step"],
    attentionSpan: "short",
    mathDifficulties: ["counting", "addition", "quantity_comparison"],
    strengths: "Boa resposta a exemplos concretos e repeticao previsivel.",
    motivators: "Objetos da casa, jogos rapidos e personagens.",
    avoidances: "Textos longos e muitas instrucoes simultaneas.",
    updatedAt: "2026-06-08",
  },
];

const mockTutorApplications = [
  {
    id: "application_ana",
    tutorId: "user_tutor_ana",
    name: "Ana Martins",
    formation: "Psicopedagogia",
    linkedin: "linkedin.com/in/anamartins",
    experience: "Experiência com TEA e reforço de matemática.",
    weeklyAvailability: "Terca e quinta, tarde",
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "application_rafael",
    tutorId: "user_tutor_rafael",
    name: "Rafael Nunes",
    formation: "Licenciatura em Matematica",
    linkedin: "linkedin.com/in/rafaelnunes",
    experience: "Aulas de reforco e atividades ludicas.",
    weeklyAvailability: "Sabado, manha",
    status: "pending",
    reviewedBy: null,
    reviewedAt: null,
  },
];

const mockSupportCycles = [
  {
    id: "cycle_joao_maria",
    childId: "child_joao",
    tutorId: "user_tutor_maria",
    startDate: "2026-06-01",
    endDate: "2026-11-30",
    currentMonth: 2,
    status: "active",
    mainGoal: "Fortalecer contagem, comparacao e somas simples.",
    currentPlan: "Soma com objetos, cartoes visuais e exemplos da rotina.",
  },
];

const mockMatches = [
  {
    id: "match_joao_maria",
    childId: "child_joao",
    tutorId: "user_tutor_maria",
    childName: "João Pereira",
    tutorName: "Maria Silva",
    reason: "Horario compativel, foco em soma simples e experiencia pedagogica.",
    compatibility: {
      schedule: true,
      mathFocus: true,
      experience: true,
    },
    status: "approved",
    createdAt: "2026-06-05",
  },
  {
    id: "match_lia_rafael",
    childId: "child_lia",
    tutorId: "user_tutor_rafael",
    childName: "Lia Costa",
    tutorName: "Rafael Nunes",
    reason: "Sabado pela manha e foco em problemas do cotidiano.",
    compatibility: {
      schedule: true,
      mathFocus: true,
      experience: false,
    },
    status: "suggested",
    createdAt: "2026-06-08",
  },
];

const mockSessions = [
  {
    id: "session_001",
    cycleId: "cycle_joao_maria",
    childId: "child_joao",
    tutorId: "user_tutor_maria",
    date: "2026-06-06",
    durationMinutes: 45,
    topic: "Soma com objetos e cartoes visuais",
    activityUsed: "Juntando quantidades",
    engagement: 4,
    difficulty: 2,
    result: "improved",
    notes: "Respondeu melhor com objetos do cotidiano.",
    nextStep: "Praticar contagem em situacoes da rotina.",
    createdAt: "2026-06-06",
  },
];

// Cada activity é um ROTEIRO de condução (estrutura fixa = previsibilidade):
// goal, setup[], steps[], ifHard, ifEasy, successSignal — espelha docs/DATABASE.md.
const mockActivities = [
  {
    id: "activity_reconhecendo_numeros",
    title: "Reconhecendo números",
    ageRange: "5-6",
    mathSkill: "number_recognition",
    format: "visual",
    difficultyLevel: 1,
    estimatedMinutes: 15,
    instructions: "Reconhecer os números de 1 a 5 com cartões e objetos da rotina.",
    goal: "Reconhecer os números de 1 a 5 com apoio visual.",
    setup: [
      "Prepare cartões com os números de 1 a 5 (papel comum serve)",
      "Escolha um lugar com pouca distração",
    ],
    steps: [
      "Mostre o cartão do 1 e fale 'um', apontando.",
      "Peça para a criança repetir.",
      "Coloque 1 objeto ao lado do cartão.",
      "Repita com o 2 e o 3, sempre com os objetos.",
      "Termine revendo os três cartões juntos.",
    ],
    ifHard: "Fique só nos números 1 e 2 hoje. Repetir está ótimo.",
    ifEasy: "Embaralhe os cartões e peça para apontar o número que você falar.",
    successSignal: "A criança aponta o número certo quando você fala, mesmo com ajuda.",
    tags: ["visual", "iniciante", "contagem"],
  },
  {
    id: "activity_contando_objetos",
    title: "Contando objetos da casa",
    ageRange: "5-6",
    mathSkill: "counting",
    format: "concrete",
    difficultyLevel: 1,
    estimatedMinutes: 15,
    instructions: "Contar pequenas quantidades usando objetos reais da rotina.",
    goal: "Contar até 10 com apoio de objetos reais.",
    setup: [
      "Separe 10 tampinhas ou brinquedos pequenos",
      "Escolha um lugar com pouca distração",
    ],
    steps: [
      "Coloque 3 objetos na mesa e conte junto, apontando.",
      "Peça: 'agora você conta'.",
      "Acrescente 1 objeto e pergunte quantos ficaram.",
      "Repita aumentando devagar, até 10.",
    ],
    ifHard: "Volte para 3 objetos e conte junto mais uma vez. Tudo bem repetir.",
    ifEasy: "Separe dois grupos e pergunte qual tem mais.",
    successSignal: "A criança aponta os objetos enquanto conta, mesmo com ajuda.",
    tags: ["concreto", "contagem", "baixa estimulação"],
  },
  {
    id: "activity_mais_ou_menos",
    title: "Mais ou menos",
    ageRange: "5-6",
    mathSkill: "comparison",
    format: "concrete",
    difficultyLevel: 1,
    estimatedMinutes: 10,
    instructions: "Perceber qual grupo tem mais usando dois conjuntos de objetos.",
    goal: "Perceber qual grupo tem mais.",
    setup: [
      "Separe objetos iguais para montar dois grupos (ex.: tampinhas)",
      "Deixe a mesa livre, só com os objetos da atividade",
    ],
    steps: [
      "Monte dois grupos bem diferentes: 3 e 6 objetos.",
      "Conte cada grupo junto com a criança.",
      "Pergunte: 'qual grupo tem mais?'.",
      "Troque os tamanhos dos grupos e repita.",
    ],
    ifHard: "Aumente a diferença entre os grupos (2 e 8) — fica mais visível.",
    ifEasy: "Aproxime as quantidades (4 e 5) e pergunte também 'qual tem menos?'.",
    successSignal: "A criança aponta o grupo maior sem precisar contar de novo.",
    tags: ["concreto", "comparação"],
  },
  {
    id: "activity_formas_pela_casa",
    title: "Formas pela casa",
    ageRange: "7-8",
    mathSkill: "shapes",
    format: "concrete",
    difficultyLevel: 1,
    estimatedMinutes: 15,
    instructions: "Reconhecer círculo, quadrado e triângulo em objetos reais.",
    goal: "Reconhecer círculo, quadrado e triângulo em objetos reais.",
    setup: [
      "Desenhe as três formas num papel",
      "Combine com a criança em qual cômodo vão procurar",
    ],
    steps: [
      "Mostre o desenho do círculo.",
      "Procurem juntos um objeto redondo (prato, relógio).",
      "Repita com o quadrado e o triângulo.",
      "No fim, revisem o que encontraram apontando no papel.",
    ],
    ifHard: "Procure só círculos hoje, num único cômodo.",
    ifEasy: "Peça para a criança desenhar a forma do objeto que encontrou.",
    successSignal: "A criança liga o objeto à forma do papel sem você nomear primeiro.",
    tags: ["concreto", "espacial", "formas"],
  },
  {
    id: "activity_sequencia_cores",
    title: "Sequência com cores suaves",
    ageRange: "7-8",
    mathSkill: "patterns",
    format: "visual",
    difficultyLevel: 1,
    estimatedMinutes: 10,
    instructions: "Continuar um padrão simples de duas cores e antecipar o próximo passo.",
    goal: "Continuar um padrão simples de duas cores.",
    setup: [
      "Separe peças de duas cores (tampinhas, blocos ou papéis)",
      "Prefira cores suaves, sem contraste forte",
    ],
    steps: [
      "Monte a sequência: azul, amarelo, azul, amarelo.",
      "Leia a sequência junto, apontando cada peça.",
      "Pergunte: 'qual vem agora?'.",
      "Deixe a criança colocar a próxima peça.",
      "Repita até a fileira ter 8 peças.",
    ],
    ifHard: "Use só 4 peças e leiam a sequência mais uma vez juntos.",
    ifEasy: "Crie um padrão com três cores e peça para a criança continuar.",
    successSignal: "A criança antecipa a próxima peça antes de você perguntar.",
    tags: ["visual", "padrões"],
  },
  {
    id: "activity_juntando_quantidades",
    title: "Juntando quantidades",
    ageRange: "7-8",
    mathSkill: "addition",
    format: "concrete",
    difficultyLevel: 2,
    estimatedMinutes: 15,
    instructions: "Entender a soma como juntar dois grupos de objetos.",
    goal: "Entender a soma como juntar dois grupos.",
    setup: [
      "Separe 10 objetos pequenos iguais",
      "Escolha um lugar com pouca distração",
    ],
    steps: [
      "Monte um grupo de 2 e um grupo de 3 objetos.",
      "Conte cada grupo apontando.",
      "Junte os dois grupos no centro da mesa.",
      "Conte o total junto com a criança.",
      "Repita com outras quantidades, até 10.",
    ],
    ifHard: "Volte para grupos de 1 e 2 e junte devagar.",
    ifEasy: "Fale a soma em voz alta ('2 mais 3') antes de juntar e pergunte o total.",
    successSignal: "A criança junta os grupos e conta o total sem pular objetos.",
    tags: ["concreto", "soma"],
  },
  {
    id: "activity_problemas_cotidiano",
    title: "Problemas simples do cotidiano",
    ageRange: "9",
    mathSkill: "word_problems",
    format: "routine",
    difficultyLevel: 2,
    estimatedMinutes: 20,
    instructions: "Interpretar perguntas matemáticas dentro de situações reais da rotina.",
    goal: "Interpretar uma pergunta matemática dentro de uma situação real.",
    setup: [
      "Pense em duas situações da rotina da criança (lanche, brinquedos)",
      "Tenha objetos por perto para encenar, se precisar",
    ],
    steps: [
      "Conte a situação: 'você tem 3 biscoitos e ganha mais 2'.",
      "Pergunte: 'com quantos você fica?'.",
      "Se precisar, encene com os objetos reais.",
      "Peça para a criança explicar como pensou.",
      "Repita com a segunda situação.",
    ],
    ifHard: "Encene tudo com objetos antes de fazer a pergunta.",
    ifEasy: "Deixe a criança inventar um problema para você resolver.",
    successSignal: "A criança traduz a história em quantidades, mesmo usando os dedos.",
    tags: ["leitura", "cotidiano", "problemas"],
  },
  {
    id: "activity_medindo_objetos",
    title: "Medindo com objetos",
    ageRange: "9",
    mathSkill: "measurement",
    format: "concrete",
    difficultyLevel: 2,
    estimatedMinutes: 15,
    instructions: "Comparar tamanhos usando uma unidade de medida não convencional.",
    goal: "Comparar tamanhos usando um objeto como unidade de medida.",
    setup: [
      "Escolha o objeto-medida (lápis, palmo ou tampinha)",
      "Escolha duas coisas para medir (livro, mesa)",
    ],
    steps: [
      "Mostre como medir o livro com o lápis.",
      "Contem juntos quantos lápis o livro tem.",
      "Peça para a criança medir a mesa do mesmo jeito.",
      "Comparem: 'qual precisou de mais lápis?'.",
    ],
    ifHard: "Meça objetos menores, que precisem de poucas repetições.",
    ifEasy: "Estimem antes ('quantos lápis você acha?') e confiram medindo.",
    successSignal: "A criança repete a unidade sem deixar espaços entre as medidas.",
    tags: ["concreto", "medidas"],
  },
  {
    id: "activity_pequena_compra",
    title: "Organizando uma pequena compra",
    ageRange: "9",
    mathSkill: "word_problems",
    format: "game",
    difficultyLevel: 2,
    estimatedMinutes: 20,
    instructions: "Somar valores pequenos numa compra simulada com itens da casa.",
    goal: "Somar valores pequenos numa situação de compra simulada.",
    setup: [
      "Monte uma 'lojinha' com 4 itens da casa e preços de 1 a 5 reais em papel",
      "Prepare dinheiro de papel ou desenhado",
    ],
    steps: [
      "Apresente a lojinha e os preços.",
      "Peça para a criança escolher 2 itens.",
      "Somem juntos o total da compra.",
      "'Paguem' com o dinheiro de papel.",
      "Troquem os papéis: agora você é quem compra.",
    ],
    ifHard: "Use só 2 itens, com preços de 1 e 2 reais.",
    ifEasy: "Introduza o troco: pague com 10 e pergunte quanto volta.",
    successSignal: "A criança soma os dois preços antes de pagar, mesmo com apoio.",
    tags: ["cotidiano", "soma", "jogo simbólico"],
  },
];

const mockProgressLogs = [
  {
    id: "progress_001",
    childId: "child_joao",
    cycleId: "cycle_joao_maria",
    skill: "addition",
    previousLevel: "precisava de ajuda constante",
    currentLevel: "resolve somas simples com objetos",
    evidence: "Completou 4 exemplos com apoio visual.",
    source: "session",
    createdAt: "2026-06-06",
  },
];

const mockReports = [
  {
    id: "report_joao_month_1",
    cycleId: "cycle_joao_maria",
    childId: "child_joao",
    tutorId: "user_tutor_maria",
    month: 1,
    summary: "Boa adaptacao ao formato visual e concreto.",
    progress: "Maior seguranca em contagem e pequenas somas.",
    difficulties: "Perde foco em atividades longas.",
    recommendations: "Manter atividades curtas com objetos familiares.",
    createdAt: "2026-06-07",
  },
];

const mockConsents = [
  {
    id: "consent_joao",
    guardianId: "user_guardian_joao",
    childId: "child_joao",
    dataUseAccepted: true,
    contactAccepted: true,
    imageUseAccepted: false,
    termsVersion: "mvp-2026-06",
    acceptedAt: "2026-06-01",
  },
];

const mockAdminNotes = [
  {
    id: "note_001",
    relatedType: "match",
    relatedId: "match_lia_rafael",
    authorId: "user_admin_cognita",
    note: "Confirmar disponibilidade do responsavel antes de aprovar o match.",
    visibility: "internal",
    createdAt: "2026-06-08",
  },
];

window.cognitaData = {
  users: mockUsers,
  children: mockChildren,
  learningProfiles: mockLearningProfiles,
  tutorApplications: mockTutorApplications,
  supportCycles: mockSupportCycles,
  matches: mockMatches,
  sessions: mockSessions,
  activities: mockActivities,
  progressLogs: mockProgressLogs,
  reports: mockReports,
  consents: mockConsents,
  adminNotes: mockAdminNotes,
};

window.cognitaMock = window.cognitaMock || {
  responsavel: {
    nome: "João Almeida",
    primeiroNome: "João",
    email: "joao@email.com",
  },
  crianca: {
    nome: "João Pereira",
    idade: "7 anos",
    etapaEscolar: "2o ano do ensino fundamental",
    foco: "Contagem, comparacao de quantidades e pequenas somas.",
  },
  tutor: {
    nome: "Maria Silva",
    primeiroNome: "Maria",
    formacao: "Pedagogia",
    disponibilidade: "Quinta-feira, 15h",
  },
  ciclo: {
    status: "Ativo",
    mesAtual: "Mês 2 de 6",
    progressoTexto: "33% do ciclo concluído",
    progressoPercentual: "33%",
    cadastro: "Validado pela equipe",
    match: "Tutor vinculado",
    presencas: "4 de 4 sessoes",
  },
  sessaoAtual: {
    dia: "Quinta-feira",
    horario: "15h",
    resumoHorario: "Quinta, 15h",
    formato: "Encontro online",
    tema: "Soma com apoio visual",
    registro: "Soma com objetos e cartoes visuais.",
  },
  atividadeSugerida: {
    titulo: "Contar objetos da casa",
    descricao: "Contar objetos da casa e comparar grupos com mais ou menos itens.",
    semana: "Semana 4",
  },
  observacaoTutor: {
    texto: "João respondeu melhor a exemplos com objetos do cotidiano.",
    tipo: "Registro",
  },
};
